import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { WorkflowBackend } from './backend.mjs';
import { WorkflowStore } from './store.mjs';
import { issueOceanIdentity } from './auth.mjs';
import { objectHash,digest } from './common.mjs';
import { TEST_VERSION,TEST_VERSION_V2,DECLARATION_SHA256,testFixtureOperation } from './test-communication.mjs';

const declaration=process.env.OCEAN_S233_DECLARATION;
assert.ok(declaration,'Verified S24.1 declaration file is required, not generated by this test');
assert.equal(digest(fs.readFileSync(declaration)),DECLARATION_SHA256);
const D=JSON.parse(fs.readFileSync(declaration));
const future=()=>new Date(Date.now()+3600000).toISOString();
function setup() {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ocean-s233-'));
  const environment={};
  const config={db_file:path.join(root,'workflow.sqlite'),test_only:true,contract_release:'2.1.0',allowed_origins:['http://localhost:3102'],python_executable:'python',
    browser:{state:'UNENROLLED',subject_id:'wayne-ocean-ui',credential_ref:'OCEAN_WAYNE_PASSWORD_SECRET'},operator_managed:true,brain_submission:'OFF',dispatch_worker:'OFF',live_real:'DISABLED',
    identities:['TELEMETRY','BRAIN','STRATEGY'].map(role=>issueOceanIdentity({identity_id:`test-s233-${role}`,role,namespace:'TEST',credential_ref:`OCEAN_${role}_TOKEN`,strategy_ids:[D.strategy_id],instance_ids:[D.instance_id],
      owner_evidence_sha256:DECLARATION_SHA256.slice(7),audience:'Ocean workflow TEST'},environment,future()))};
  // Isolated software fixture only; this does not enroll or impersonate Wayne.
  const bootstrap=new WorkflowStore(config.db_file);
  for(const identity of config.identities)bootstrap.registerIdentity(identity);
  bootstrap.close();
  const backend=new WorkflowBackend(config,environment);
  const state={config,environment};
  const actors={};
  for(const identity of config.identities) {
    const actor={id:identity.identity_id,role:identity.role,scopes:identity.scopes || {TELEMETRY:['read','health.write','event.write'],BRAIN:['read','artifact.write','event.write'],STRATEGY:['read','artifact.write','delivery']}[identity.role],strategyIds:identity.strategy_ids,instanceIds:identity.instance_ids};
    const instruction='S23.3 synthetic instruction. No strategy approval.';
    const expiry=future();
    const req={fixture_id:`test-fixture-${identity.role}`,identity_id:actor.id,declaration_path:declaration,declaration_sha256:DECLARATION_SHA256,expires_at_utc:expiry,
      correlation:{job_id:'test-job',event_id:'test-event',input_sha256:digest('synthetic-input')},
      handoff:identity.role==='STRATEGY'?{handoff_id:'test-handoff',revision:1,expires_at_utc:expiry,instruction_md:instruction,instruction_sha256:digest(instruction),baseline_sha256:digest('synthetic baseline only')}:null};
    testFixtureOperation({state,operator_id:'S-1-isolated',action:'test-prepare',request:req},backend.store);
    actors[identity.role]={actor,req};
  }
  let seq=0;
  const input=(role,operation,data,message)=>({schema_version:TEST_VERSION,message_id:message || `test-message-${++seq}`,fixture_id:actors[role].req.fixture_id,declaration_sha256:DECLARATION_SHA256,strategy_id:D.strategy_id,instance_id:D.instance_id,operation,data});
  return {root,backend,config,state,actors,input,close(){this.backend.close();fs.rmSync(root,{recursive:true,force:true});}};
}
test('Nonphysical durable receipts, duplicates/conflicts, strict scopes, restart and no factual registration',()=>{
  const a=setup();try{
    const t=a.backend.testCommunication,actor=a.actors.TELEMETRY.actor;
    const capabilities=t.readiness(actor,TEST_VERSION);
    assert.equal(capabilities.version,TEST_VERSION);
    assert.equal(Object.hasOwn(capabilities,'terminal_callback_statuses'),false);
    const body=a.input('TELEMETRY','health.report',{status:'READY',next_owner:'Ocean',next_action:'Synthetic only'});
    const first=t.write(actor,body);assert.equal(first.payload_sha256,objectHash(body));assert.deepEqual(t.write(actor,body),first);
    assert.deepEqual(t.receipt(actor,first.receipt_id),first);
    assert.throws(()=>t.write(actor,{...body,data:{...body.data,status:'DEGRADED'}}),/TEST_DUPLICATE_CONFLICT/);
    assert.deepEqual(t.receipt(actor,first.receipt_id),first);
    assert.equal(a.backend.db.prepare('SELECT COUNT(*) n FROM ow_test_conflicts').get().n,1);
    for(const [field,value,error] of [['strategy_id','other_strategy','WRONG_STRATEGY_SCOPE'],['instance_id','test-other','WRONG_INSTANCE_SCOPE'],['declaration_sha256',digest('other'),'TEST_DECLARATION_SUBSTITUTION']]) assert.throws(()=>t.write(actor,{...body,[field]:value}),new RegExp(error));
    assert.throws(()=>t.write({...actor,scopes:['read']},body),/WRONG_ACTION_SCOPE/);
    assert.throws(()=>t.receipt(a.actors.BRAIN.actor,first.receipt_id),/TEST_WRONG_CALLER/);
    assert.throws(()=>a.backend.authorize(actor,'health.write',D.strategy_id,D.instance_id),/ENTITY_NOT_FOUND/);
    for(const table of ['ow_instances','ow_runs','ow_cases','ow_events','ow_artifacts','ow_outbox','ow_decisions'])assert.equal(a.backend.db.prepare(`SELECT COUNT(*) n FROM ${table}`).get().n,0);
    a.backend.close();a.backend=new WorkflowBackend(a.config,a.state.environment);
    assert.deepEqual(a.backend.testCommunication.receipt(actor,first.receipt_id),first);
  }finally{a.close();}
});
test('Strategy fixture handoff has ordered acknowledgement/progress/result, hashes and content access',()=>{
  const a=setup();try{
    const {actor,req}=a.actors.STRATEGY,t=a.backend.testCommunication;
    const f=t.readFixture(actor,req.fixture_id), h=f.handoff;
    const artifact=t.write(actor,a.input('STRATEGY','artifact.register',{content:'synthetic result',content_sha256:digest('synthetic result')}));
    const keys={handoff_id:h.handoff_id,handoff_revision:h.revision,instruction_sha256:h.instruction_sha256,baseline_sha256:h.baseline_sha256};
    assert.throws(()=>t.write(actor,a.input('STRATEGY','handoff.progress',keys)),/STATE_CONFLICT/);
    assert.throws(()=>t.write(actor,a.input('STRATEGY','handoff.ack',{...keys,handoff_revision:2})),/BINDING_MISMATCH/);
    for(const operation of ['handoff.ack','handoff.progress'])assert.equal(t.write(actor,a.input('STRATEGY',operation,keys)).persisted,true);
    assert.equal(t.write(actor,a.input('STRATEGY','handoff.result',{...keys,result_receipt_id:artifact.receipt_id,result_sha256:artifact.data.content_sha256})).state,'COMPLETED');
  }finally{a.close();}
});
test('Brain result and callback require exact job, event, input and result hash; operator cleanup reauthorizes retries',()=>{
  const a=setup();try{
    const {actor,req}=a.actors.BRAIN,t=a.backend.testCommunication;
    const body=a.input('BRAIN','result.register',{correlation:req.correlation,content:'synthetic worker result',content_sha256:digest('synthetic worker result')});
    const result=t.write(actor,body);
    const cb=a.input('BRAIN','result.callback',{correlation:req.correlation,result_receipt_id:result.receipt_id,result_sha256:result.data.content_sha256,status:'COMPLETED'});
    assert.throws(()=>t.write(actor,{...cb,data:{...cb.data,correlation:{...req.correlation,job_id:'test-other'}}}),/CORRELATION_MISMATCH/);
    assert.throws(()=>t.write(actor,{...cb,data:{...cb.data,result_sha256:digest('tampered')}}),/RESULT_REFERENCE_MISMATCH/);
    assert.equal(t.write(actor,cb).persisted,true);
    assert.equal(testFixtureOperation({state:a.state,operator_id:'S-1-isolated',action:'test-cleanup',request:{fixture_id:req.fixture_id}},a.backend.store).active,false);
    assert.throws(()=>t.write(actor,body),/TEST_FIXTURE_INACTIVE/);
    assert.throws(()=>testFixtureOperation({state:a.state,operator_id:'S-1-isolated',action:'test-prepare',request:req},a.backend.store),/IMMUTABLE_TEST_FIXTURE_CONFLICT/);
  }finally{a.close();}
});
for (const status of ['COMPLETED','ERROR','TIMEOUT','INCOMPLETE']) {
  test(`Versioned Brain ${status} callback is persisted once with exact result lineage`,()=>{
    const a=setup();try{
      const {actor,req}=a.actors.BRAIN,t=a.backend.testCommunication;
      const content=JSON.stringify({outcome:status,classification:'SYNTHETIC_COMMUNICATION_ONLY'});
      const result=t.write(actor,a.input('BRAIN','result.register',{correlation:req.correlation,content,content_sha256:digest(content)}));
      const cb={...a.input('BRAIN','result.callback',{correlation:req.correlation,result_receipt_id:result.receipt_id,
        result_sha256:result.data.content_sha256,status}),schema_version:TEST_VERSION_V2};
      assert.deepEqual(t.readiness(actor,TEST_VERSION_V2).terminal_callback_statuses,['COMPLETED','ERROR','TIMEOUT','INCOMPLETE']);
      if(status!=='COMPLETED')assert.throws(()=>t.write(actor,{...cb,schema_version:TEST_VERSION}),/TEST_CALLBACK_STATUS_INVALID/);
      assert.throws(()=>t.write(actor,{...cb,data:{...cb.data,result_sha256:digest('wrong')}},TEST_VERSION_V2),/TEST_RESULT_REFERENCE_MISMATCH/);
      const saved=t.write(actor,cb,TEST_VERSION_V2);
      assert.equal(saved.schema_version,TEST_VERSION_V2);assert.equal(saved.persisted,true);assert.equal(saved.data.status,status);
      assert.deepEqual(t.receipt(actor,saved.receipt_id),saved);
      assert.deepEqual(t.write(actor,cb,TEST_VERSION_V2),saved);
      assert.throws(()=>t.write(actor,{...cb,message_id:'test-other-terminal'},TEST_VERSION_V2),/TEST_TERMINAL_CALLBACK_CONFLICT/);
      assert.throws(()=>t.receipt(a.actors.STRATEGY.actor,saved.receipt_id),/TEST_WRONG_CALLER/);
      a.backend.close();a.backend=new WorkflowBackend(a.config,a.state.environment);
      assert.deepEqual(a.backend.testCommunication.receipt(actor,saved.receipt_id),saved);
    }finally{a.close();}
  });
}
test('Schema, payload, secret and operator authority boundaries',()=>{
  const a=setup();try{
    const {actor,req}=a.actors.BRAIN,t=a.backend.testCommunication;
    const body=a.input('BRAIN','artifact.register',{content:'x',content_sha256:digest('x')});
    assert.throws(()=>t.write(actor,{...body,approval:true}),/UNKNOWN_OR_AUTHORITY_FIELD/);
    assert.throws(()=>t.write(actor,{...body,data:{...body.data,content_sha256:digest('bad')}}),/CONTENT_HASH_MISMATCH/);
    assert.throws(()=>t.write(actor,{...body,data:{...body.data,content:'x'.repeat(60000)}}),/PAYLOAD_TOO_LARGE/);
    assert.throws(()=>t.write(actor,{...body,data:{content:'Bearer fake-secret-content',content_sha256:digest('Bearer fake-secret-content')}}),/SECRET_CONTENT_REJECTED/);
    assert.throws(()=>testFixtureOperation({state:a.state,operator_id:'service',action:'test-prepare',request:req},a.backend.store),/WINDOWS_OPERATOR_SID_REQUIRED/);
    assert.throws(()=>testFixtureOperation({state:a.state,operator_id:'S-1-isolated',action:'test-prepare',request:{...req,declaration_path:'relative.json'}},a.backend.store),/ABSOLUTE_TEST_DECLARATION_PATH_REQUIRED/);
    assert.throws(()=>t.write({...actor,role:'HUMAN'},body),/TEST_SERVICE_ONLY/);
  }finally{a.close();}
});
test('Exact stored-byte bound rejects a receipt whose envelope exceeds remaining capacity',()=>{
  const a=setup();try{
    const t=a.backend.testCommunication,actor=a.actors.TELEMETRY.actor;
    // Isolated accounting fixture: no deployed metadata or consumer is modified.
    const body=a.input('TELEMETRY','health.report',{status:'READY',next_owner:'Ocean',next_action:'Synthetic only'});
    const first=t.write(actor,body);
    const storedBytes=Buffer.byteLength(JSON.stringify(first))+Buffer.byteLength(JSON.stringify(body));
    assert.ok(3*Buffer.byteLength(JSON.stringify(body))<storedBytes-1);
    a.backend.db.prepare('INSERT INTO ow_test_receipts VALUES(?,?,?,?,?,?,?,?,?)').run('test-limit-row',actor.id,a.actors.TELEMETRY.req.fixture_id,'test-limit-row','health.report',digest('x'),'{}','{}',64*1024*1024-2*storedBytes+1);
    assert.throws(()=>t.write(actor,{...body,message_id:'test-message-2'}),/TEST_STORAGE_CAPACITY/);
    assert.equal(a.backend.db.prepare('SELECT COUNT(*) n FROM ow_test_receipts').get().n,2);
  }finally{a.close();}
});
